config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
    put "like", to: "posts#like"
  end
  resources :users, only: :index
  resources :friend_requests

  post "/sign_up_validation", to: "users/omniauth_callbacks#sign_up_validation"
  get "/favorites", to: "posts#favorites", as: :favorites
  get "/profile/:id", to: "users#profile", as: :profile
  get "/profile/:id/friends", to: "friends#index", as: :friends
  delete "/friends/:id", to: "friends#destroy", as: :destroy_friend

  devise_for :users, controllers: {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  authenticated :user do
    root 'posts#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true
  default_scope { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:destroy]

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to @post
    else
      render edit_post(@post)
    end
  end

  def destroy
    if @comment.destroy
      redirect_to @post
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.friendly.find(params[:post_id])
  end

  def set_comment
    set_post
    @comment = @post.comments.find(params[:id])
  end
end

app/views/comments/_comment.html.haml
.box
  %article.media
    .media-left
      %figure.image.is-64x64
        - if comment.user.image.nil?
          %img(src="https://bulma.io/images/placeholders/64x64.png" alt="Image")
        - else
          %img(src="#{comment.user.image}" alt="Image")
    .media-content
      .content
        %p
          %strong
            = print_name(comment.user)
          %small.has-text-weight-semibold
            = print_username(comment.user)
          %small.is-italic.is-pulled-right= time_ago_in_words(comment.created_at)
          %br
          = comment.content
      - if comment.user.id == current_user.id
        %nav.level.is-mobile.post-icons-container
          .level-left
            = link_to post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Estas seguro?" }, class: 'level-item' do
              %span.icon.is-small
                = fa_icon "trash"

app/views/comments/_form.html.haml
#comment-modal.modal
  .modal-background
  .modal-card
    %header.modal-card-head
      %p.modal-card-title Comenta
      %button#comment-close-button.modal-close.is-large.delete(aria-label="close")
    %section.modal-card-body
      = form_for ([@post, @post.comments.build]) do |f|
        .field
          = f.label "Mensaje", class: "label"
          .control
            = f.text_area :content, class: "textarea"

        .actions
          = f.submit 'Comentar', class: "button is-primary"