config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
    put "like", to: "posts#like"
  end
  resources :users, only: :index
  resources :friend_requests

  post "/sign_up_validation", to: "users/omniauth_callbacks#sign_up_validation"
  get "/favorites", to: "posts#favorites", as: :favorites
  get "/profile/:id", to: "users#profile", as: :profile
  get "/profile/:id/friends", to: "friends#index", as: :friends
  delete "/friends/:id", to: "friends#destroy", as: :destroy_friend

  devise_for :users, controllers: {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  authenticated :user do
    root 'posts#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end
end

app/views/partials/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in pv20">
      <a href="#" data-dismiss="alert" class="delete">×</a>
      <h3 class="title is-5"><%= value %></h3>
    </div>
  <% end %>
</div>

app/views/partials/_header.html.haml
%nav.navbar.is-fixed-top(role="navigation" aria-label="main navigation")
  .container
    .navbar-brand
      %a.navbar-item(href="/")
        %span.title.is-2.title-header.mv10 Tweety

      %button.button.navbar-burger
        %span
        %span
        %span

    .navbar-menu
      .navbar-start
        .navbar-item
          = link_to "Publica", new_post_path
      .navbar-end
        .navbar-item
          = form_tag(users_path, :method => "get", id: "search-form") do
            .field.has-addons
              .control
                = submit_tag "Buscar", class: "button is-info"
              .control
                = text_field_tag :search, params[:search], class: "input", placeholder: "Busca a tus amigos"
        .navbar-item
          = link_to favorites_path do
            = fa_icon "heart", class: "red"
        .navbar-item
          %figure.image.is-32x32.mr10
            - if current_user.image.url.nil?
              %img.round-image(src="https://bulma.io/images/placeholders/32x32.png")
            - else
              %img.round-image(src="#{current_user.image.small.url}")
          = print_username(current_user)
        .navbar-item
          = link_to "Perfil", profile_path(current_user.id), class: "#{'friend-requests-count' if friend_request_count > 0}", data: { badge: "#{friend_request_count}" }
        .navbar-item
          = link_to "Salir", destroy_user_session_path, method: :delete

app/views/partials/_post_card.html.haml
.box
  %article.media
    .media-left
      %figure.image.is-64x64
        - if post.user.image.url.nil?
          %img.round-image(src="https://bulma.io/images/placeholders/64x64.png" alt="Image")
        - else
          %img.round-image(src="#{post.user.image.medium.url}" alt="Image")
    .media-content
      .content
        %p
          %strong
            = link_to post.name, post_path(post)
          %small.has-text-weight-semibold
            = print_username(post.user)
          %small.is-italic.is-pulled-right= time_ago_in_words(post.created_at)
          %br
          = post.content
      %nav.level.is-mobile.post-icons-container
        .level-left
          = link_to post_path(post), class: 'level-item' do
            %span.icon.is-small
              = fa_icon "comment"
              %span.counter= post.comments_count
          %a.level-item
            %span.icon.is-small
              = fa_icon "retweet"
              %span.counter 12
          = link_to post_like_path(post), class:"level-item", method: :put, remote: true do
            %span.icon.is-small
              - if post.get_upvotes.size > 0
                = fa_icon "heart", id: "like-button-#{post.id}", class: "red"
              - else
                = fa_icon "heart-o", id: "like-button-#{post.id}"
              %span.counter(id="likes-counter-#{post.id}")= post.get_upvotes.size

app/views/partials/_user_card.html.haml
.box
  %article.media
    .media-left
      %figure.image.is-64x64
        - if user.image.url.nil?
          %img.round-image(src="https://bulma.io/images/placeholders/64x64.png" alt="Image")
        - else
          %img.round-image(src="#{user.image.medium.url}" alt="Image")
    .media-content
      .content
        %p.title.is-5
          %strong
            = link_to profile_path(user.id) do
              = print_username(user)
        %span= user.email
        %br
        %span= print_name(user)
      %nav.level.is-mobile.post-icons-container
        .level-left
          - if current_user.id != user.id
            - if outgoing_friend_requests?(user)
              %span.level-item Enviada
            - elsif invitation and incoming_friend_requests?
              = link_to "Aceptar", friend_request_path(invitation), method: :put, class: "level-item"
            - elsif is_friend?(user)
              = link_to "Eliminar", destroy_friend_path(user.id), method: :delete, class: "level-item", data: { confirm: "Estas seguro?" }
            - else
              = link_to "Agregar a amigos", friend_requests_path(friend_id: user.id), method: :post, class: 'level-item'
          - else
            = link_to edit_user_registration_path, class: 'level-item' do
              %span.icon.is-small
                = fa_icon "star", class: "yellow"