config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
    put "like", to: "posts#like"
  end
  resources :users, only: :index
  resources :friend_requests

  post "/sign_up_validation", to: "users/omniauth_callbacks#sign_up_validation"
  get "/favorites", to: "posts#favorites", as: :favorites
  get "/profile/:id", to: "users#profile", as: :profile
  get "/profile/:id/friends", to: "friends#index", as: :friends
  delete "/friends/:id", to: "friends#destroy", as: :destroy_friend

  devise_for :users, controllers: {
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations"
  }

  authenticated :user do
    root 'posts#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  mount_uploader :image, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:facebook]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.remote_image_url = auth.info.image
    end
  end

  def self.search(search)
    where("email LIKE ?", "%#{search}%").or(where("name LIKE ?", "%#{search}%"))
  end

  def remove_friend(user, friend)
    user.friends.destroy(friend)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      @user.remember_me = true
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.auth"] = request.env["omniauth.auth"]
      render :edit
    end
  end

  def sign_up_validation
    @user = User.from_omniauth(session["devise.auth"])

    if @user.update(user_params)
      sign_in_and_redirect @user, event: :authentication
    else
      render :edit
    end
  end

  def failure
    redirect_to new_user_session_path, notice: "Ocurrio un error con el login, intenta de nuevo" 
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "application", only: [:edit, :update]

  protected

  # This method allows to user update
  # the profile without password
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # After user updates the profile this
  # method redirects to edit profile
  def after_update_path_for(resource)
    edit_user_registration_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search]
      @users = User.search(params[:search]).order(email: :asc)
    else
      @users = User.all.order(email: :asc)
    end
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.haml
.columns.is-multiline
  - if @users.present?
    - @users.each do |user|
      .column.is-one-third
        = render "partials/user_card", user: user, invitation: false
  - else
    .column.is-12.has-text-centered
      .box
        %h3.title.is-3
          No hay usuarios que contengan en su correo o nombre
        %h4.subtitle.is-3.has-text-weight-bold (#{params[:search]})

app/views/users/profile.html.haml
.columns
  .column.is-three-fifths.is-offset-one-fifth
    .card.profile
      .card-content
        %figure.image.is-128x128
          - if @user.image.url.nil?
            %img.round-image(src="https://bulma.io/images/placeholders/32x32.png")
          - else
            %img.round-image(src="#{@user.image.big.url}")
        .has-text-centered.mt20
          %p.title.is-3= @user.email

          - if !@user.username.empty?
            %p.subtitle.is-5 @#{@user.username}
          - else
            %p.subtitle.is-5
              = link_to "Escribe tu usuario", edit_user_registration_path

          - if !@user.name.nil?
            %p.subtitle.is-5= @user.name
          - else
            %p.subtitle.is-5
              = link_to "Escribe tu nombre", edit_user_registration_path
      %footer.card-footer
        = link_to "Amigos (#{@user.friends.count})", friends_path, class: "card-footer-item"
        - if @user.id == current_user.id
          = link_to "Invitaciones (#{friend_request_count})", friend_requests_path, class: "card-footer-item"
          = link_to "Configuración", edit_user_registration_path, class: "card-footer-item"
.columns
  .column.is-half.is-offset-one-quarter
    - @user.posts.each do |post|
      = render "partials/post_card", post: post